### PR TITLE
Content for screen 1

### PR DESCRIPTION
**Pull request by sharonwarner**
Screen Shot 2020-04-24 at 3 54 31 PM

Screen Shot 2020-04-24 at 3 54 44 PM

### CODE REVIEW

**Comment by kalvinwang** [comment]
I think a big chunk of the middle is missing from the screenshot, want to try this convenient chrome extension that captures the whole page? https://chrome.google.com/webstore/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg?hl=en

"Receive Your Benefits" should be linked
on the last two links, "apply for" should be linked (checked figma + doc)

**Comment by nguyen-tina** [comment]
We've also changed the title of this page to "Benefits you can apply for", and removed the first tab of the floating menu (we consolidated that content to the last page, More resources)

**Comment by kalvinwang** [comment]
@nguyen-tina no worries, that's already on master, just not merged onto sharon's branch yet (it was in my sidebar PR)

**Comment by sharonwarner** [comment]
@nguyen-tina that's fixed in a separate PR!

**Comment by sharonwarner** [comment]
@kalvinwang oh that's a cool plugin! thanks! updating the links now... i was waiting for the sidebar updates because the Receive Your Benefits link goes to a different tab!

**Comment by kalvinwang** [comment]
@sharonwarner uh bad news you can't use a href attribute to get to the other tab cause we don't have routing 😬 but you can copy the onclick from tabbed-container!

**Pull request merged**
